# ui-data-import.R

fluidPage(fluidRow(column(
  3,
  tabBox(
    title = "",
    id = "datasource",
    width = NULL,
    # tabPanel(
    #   tagList(icon("folder-open"), "Sample"),
    #   uiOutput("dataSourceSelect"),
    #   tags$p("1. The 10000 genes dataset", tags$b("hypoData"), "is simulation data generated by", tags$code("TCC::simulateReadCounts"), "function"),
    #   tags$p("2. After performing simulation in the", tags$code("Step0"), ",", tags$code("Simulation Data"), "can be selected and it's referring the latest simulation result."),
    #   do.call(actionBttn, c(
    #     list(
    #       inputId = "CountDataSample",
    #       label = "1. Import Count Data",
    #       icon = icon("play")
    #     ),
    #     actionBttnParams
    #   ))
    # ),
    tabPanel(
      tagList(icon("cloud-upload"), "Upload"),
      fileInput(
        "uploadCountData",
        "Upload Count Data",
        accept = c("text/csv",
                   "text/comma-separated-values,text/plain",
                   ".csv"),
        buttonLabel = "Upload...",
        placeholder = "No file has been uploaded."
      ),
      helpText("Text file in .tsv/.csv format, and the first column should be genes' name.")
    )
  )
  ,
  box(
    title = tagList(icon("tags"), "Group Assignment"),
    solidHeader = TRUE,
    status = "primary",
    width = NULL,
    fileInput(
      "uploadGroupData",
      "Upload Group Data",
      accept = c("text/csv",
                 "text/comma-separated-values,text/plain",
                 ".csv"),
      buttonLabel = "Upload Group...",
      placeholder = "No file has been uploaded."
    ),
    do.call(actionBttn, c(
      list(
        inputId = "confirmedGroupList",
        label = "2. Assign Group Label",
        icon = icon("play")),
        actionBttnParams
      )
    ),
    footer = HTML("Upload a .csv file with no header and samplename,groupname for each sample<br/>Example:<br/>Sample1,Group1<br/>Sample2,Group1<br/>Sample3,Group2<br/>...")
  ),
  box(
    title = tagList(icon("info-circle"), "Summary"),
    solidHeader = TRUE,
    status = "info",
    width = NULL,
    uiOutput("importDataSummary")
  )
),
column(
  9,
  box(
    title = tagList(icon("table"), "Read Count Table"),
    solidHeader = TRUE,
    status = "info",
    width = NULL,
    uiOutput("emptyTable")
  ),
  tabBox(
    title = "",
    width = NULL,
    tabPanel(
      title = tagList(icon("bar-chart"), "Count Distribution"),
      uiOutput("sampleDistributionBoxPanel")
    ),
    tabPanel(
      title = tagList(icon("filter"), "Filtering Threshold"),
      uiOutput("lowCountFilterByCutoffUI")
    ),
    tabPanel(
      title = tagList(icon("area-chart"), "Density Plot"),
      uiOutput("sampleDistributionDensityPanel")
    ),
    tabPanel(title = tagList(icon("object-group"), "MDS Plot"),
             uiOutput("mdsUI")),
    tabPanel(title = tagList(icon("object-group"), "PCA"),
             uiOutput("pcaUI")),
    tabPanel(title = tagList(icon("sitemap"), "Hierarchical Clustering"),
             uiOutput("dendUI"))
  )
)))
